# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfoHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenter', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
