# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPortal', '0004_bipnic_biportgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bivswitch',
            name='host',
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudPortal.BiHost'),
        ),
    ]
