# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPortal', '0005_auto_20161101_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihost',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bihost',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bihost',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bipnic',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bipnic',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bipnic',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biportgroup',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biportgroup',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='biportgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bivirtualmachine',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bivirtualmachine',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bivirtualmachine',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='dbstatus',
            field=models.CharField(default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
