# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPortal', '0008_auto_20161102_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='bivirtualmachine',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudPortal.BiHost'),
        ),
    ]
