# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudPortal', '0011_auto_20161103_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bivswitch',
            name='host',
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='host',
            field=models.ManyToManyField(to='cloudPortal.BiHost'),
        ),
    ]
