# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_host', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_user', models.CharField(blank=True, max_length=30, null=True)),
                ('vc_pass', models.CharField(blank=True, max_length=30, null=True)),
                ('vc_port', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
