# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0002_baseinfohost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiVirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=20, null=True)),
                ('macAddress', models.CharField(blank=True, max_length=20, null=True)),
                ('cpuUsage', models.CharField(blank=True, max_length=5, null=True)),
                ('memUsage', models.CharField(blank=True, max_length=5, null=True)),
                ('netUsage', models.CharField(blank=True, max_length=5, null=True)),
                ('stgUsage', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiVnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ('ipAddress',),
            },
        ),
        migrations.CreateModel(
            name='BiVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiVswitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BaseInfoHost',
            new_name='BiHost',
        ),
        migrations.AlterModelOptions(
            name='bihost',
            options={'ordering': ('datacenter', 'cluster', 'host')},
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='host',
            field=models.ManyToManyField(to='ux.BiHost'),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='host',
            field=models.ManyToManyField(to='ux.BiHost'),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='host',
            field=models.ManyToManyField(to='ux.BiHost'),
        ),
    ]
