# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0007_auto_20161102_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipnic',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biportgroup',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='mac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bivnic',
            name='portgroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='capacity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bivolume',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='numPorts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bivswitch',
            name='numPortsAvailable',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='bipnic',
            name='vswitch',
        ),
        migrations.AddField(
            model_name='bipnic',
            name='vswitch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ux.BiVswitch'),
        ),
        migrations.RemoveField(
            model_name='biportgroup',
            name='vswitch',
        ),
        migrations.AddField(
            model_name='biportgroup',
            name='vswitch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ux.BiVswitch'),
        ),
    ]
