# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0009_bivirtualmachine_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bivolume',
            name='host',
        ),
        migrations.AddField(
            model_name='bivolume',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ux.BiHost'),
        ),
    ]
