# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0010_auto_20161102_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bivolume',
            options={'ordering': ('name',)},
        ),
    ]
