# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0012_auto_20161103_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bivolume',
            name='host',
        ),
        migrations.AddField(
            model_name='bivolume',
            name='host',
            field=models.ManyToManyField(to='ux.BiHost'),
        ),
    ]
