# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0013_auto_20161103_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='bivirtualmachine',
            name='network',
            field=models.ManyToManyField(to='ux.BiPortgroup'),
        ),
    ]
