# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0015_useraddinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiFaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('faultType', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('occur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('hwtype', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('firmwareVersion', models.CharField(blank=True, max_length=100, null=True)),
                ('mfgtime', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=20, null=True)),
                ('lastModified', models.DateTimeField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
