# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0016_bifaults_biinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('val', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('is_used', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
