# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0017_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_name', models.CharField(blank=True, max_length=100, null=True)),
                ('applications', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_type', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_id', models.CharField(blank=True, max_length=100, null=True)),
                ('folder', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_description', models.CharField(blank=True, max_length=100, null=True)),
                ('cloud', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
