# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0018_bicatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicatalog',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
