# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0019_bicatalog_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicatalog',
            name='catalog_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
