# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0020_auto_20161121_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bivirtualmachine',
            name='ucsd_vm_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
