# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0022_udcloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('total_vm', models.IntegerField(default=0)),
                ('total_cpu', models.IntegerField(default=0)),
                ('total_mem', models.IntegerField(default=0)),
                ('total_stg', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardVswitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('switch', models.CharField(blank=True, max_length=100, null=True)),
                ('portgroup', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
