# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0023_dashboardalloc_dashboardvswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('group_id', models.IntegerField(default=0)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_group_id', models.IntegerField(default=0)),
                ('parent_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('group_type', models.IntegerField(default=0)),
                ('enable_budget', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
