# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0024_udgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdVDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbstatus', models.CharField(default=b'A', max_length=1)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('vdc_id', models.IntegerField(default=0)),
                ('custom_categories', models.IntegerField(default=0)),
                ('total_vms', models.IntegerField(default=0)),
                ('active_vms', models.IntegerField(default=0)),
                ('dcloud', models.CharField(blank=True, max_length=100, null=True)),
                ('vdc', models.CharField(blank=True, max_length=100, null=True)),
                ('approvers', models.CharField(blank=True, max_length=100, null=True)),
                ('lock_state', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('cloud', models.CharField(blank=True, max_length=100, null=True)),
                ('vdc_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
